-- Public development seed.
--
-- Intentionally empty by default.
--
-- Portfolio holdings, transactions, account holders, provider mappings and
-- other deployment-specific financial data must not be committed here.
--
-- For an explicit LOCAL-ONLY fictional dataset, run:
--
--   npm run demo:reset
--
-- The opt-in demo bootstrap lives in scripts/bootstrap-public-demo.mjs.
-- It refuses a non-loopback Supabase API URL and does not modify .env.local.
