export const DEFAULT_ASSET_CLASSES = [
  {
    code: "polish_stocks",
    name: "Polish stocks",
    colorHex: "#1F3A8A",
    sortOrder: 1,
    includeInAllocationChart: true,
    includeInXirr: true,
  },
  {
    code: "polish_government_bonds",
    name: "Polish government bonds",
    colorHex: "#8D99AE",
    sortOrder: 2,
    includeInAllocationChart: true,
    includeInXirr: true,
  },
  {
    code: "global_etfs",
    name: "Global ETFs",
    colorHex: "#7C3AED",
    sortOrder: 3,
    includeInAllocationChart: true,
    includeInXirr: true,
  },
  {
    code: "bitcoin",
    name: "Bitcoin",
    colorHex: "#F2A900",
    sortOrder: 4,
    includeInAllocationChart: true,
    includeInXirr: true,
  },
  {
    code: "us_reits",
    name: "U.S. REITs",
    colorHex: "#E76F51",
    sortOrder: 5,
    includeInAllocationChart: true,
    includeInXirr: true,
  },
  {
    code: "semiconductor_stocks",
    name: "Semiconductor stocks",
    colorHex: "#0EA5A4",
    sortOrder: 6,
    includeInAllocationChart: true,
    includeInXirr: true,
  },
  {
    code: "ppk",
    name: "Employee Capital Plans (PPK)",
    colorHex: "#C06C84",
    sortOrder: 7,
    includeInAllocationChart: true,
    includeInXirr: false,
  },
] as const;